# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'cameraOptionsForm.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDoubleSpinBox, QFrame, QLabel, QPushButton,
    QScrollArea, QSizePolicy, QSlider, QSpinBox,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(800, 410)
        self.frameBlue = QFrame(Form)
        self.frameBlue.setObjectName(u"frameBlue")
        self.frameBlue.setGeometry(QRect(0, 0, 280, 410))
        self.frameBlue.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameBlue.setFrameShadow(QFrame.Shadow.Raised)
        self.lblTitle = QLabel(self.frameBlue)
        self.lblTitle.setObjectName(u"lblTitle")
        self.lblTitle.setGeometry(QRect(0, 20, 240, 50))
        self.lblDescription = QLabel(self.frameBlue)
        self.lblDescription.setObjectName(u"lblDescription")
        self.lblDescription.setGeometry(QRect(20, 270, 231, 121))
        self.lblDescription.setWordWrap(True)
        self.lblCvImg = QLabel(self.frameBlue)
        self.lblCvImg.setObjectName(u"lblCvImg")
        self.lblCvImg.setGeometry(QRect(20, 110, 241, 141))
        self.frameButtons = QFrame(Form)
        self.frameButtons.setObjectName(u"frameButtons")
        self.frameButtons.setGeometry(QRect(280, 0, 520, 410))
        self.frameButtons.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameButtons.setFrameShadow(QFrame.Shadow.Raised)
        self.btnBack = QPushButton(self.frameButtons)
        self.btnBack.setObjectName(u"btnBack")
        self.btnBack.setGeometry(QRect(360, 340, 120, 40))
        self.btnSave = QPushButton(self.frameButtons)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setGeometry(QRect(230, 340, 120, 40))
        self.scrollArea = QScrollArea(self.frameButtons)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(30, 10, 471, 311))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 469, 309))
        self.lblConfidence = QLabel(self.scrollAreaWidgetContents)
        self.lblConfidence.setObjectName(u"lblConfidence")
        self.lblConfidence.setGeometry(QRect(20, 150, 191, 30))
        self.lblHue = QLabel(self.scrollAreaWidgetContents)
        self.lblHue.setObjectName(u"lblHue")
        self.lblHue.setGeometry(QRect(20, 30, 161, 30))
        self.lblCamera = QLabel(self.scrollAreaWidgetContents)
        self.lblCamera.setObjectName(u"lblCamera")
        self.lblCamera.setGeometry(QRect(20, 0, 161, 30))
        self.comboCamera = QComboBox(self.scrollAreaWidgetContents)
        self.comboCamera.setObjectName(u"comboCamera")
        self.comboCamera.setGeometry(QRect(270, 10, 181, 31))
        self.sliderHue = QSlider(self.scrollAreaWidgetContents)
        self.sliderHue.setObjectName(u"sliderHue")
        self.sliderHue.setGeometry(QRect(190, 50, 271, 31))
        self.sliderHue.setOrientation(Qt.Orientation.Horizontal)
        self.spinConfidence = QSpinBox(self.scrollAreaWidgetContents)
        self.spinConfidence.setObjectName(u"spinConfidence")
        self.spinConfidence.setGeometry(QRect(390, 120, 60, 31))
        self.spinConfidence.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lblFrameCnt = QLabel(self.scrollAreaWidgetContents)
        self.lblFrameCnt.setObjectName(u"lblFrameCnt")
        self.lblFrameCnt.setGeometry(QRect(20, 170, 301, 30))
        self.spinFrameCnt = QSpinBox(self.scrollAreaWidgetContents)
        self.spinFrameCnt.setObjectName(u"spinFrameCnt")
        self.spinFrameCnt.setGeometry(QRect(390, 140, 60, 31))
        self.spinFrameCnt.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lblDelay = QLabel(self.scrollAreaWidgetContents)
        self.lblDelay.setObjectName(u"lblDelay")
        self.lblDelay.setGeometry(QRect(20, 190, 341, 70))
        self.spinDelay = QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.spinDelay.setObjectName(u"spinDelay")
        self.spinDelay.setGeometry(QRect(390, 160, 60, 25))
        self.spinDelay.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lblSensitivity = QLabel(self.scrollAreaWidgetContents)
        self.lblSensitivity.setObjectName(u"lblSensitivity")
        self.lblSensitivity.setGeometry(QRect(20, 230, 131, 30))
        self.sliderSensitivity = QSlider(self.scrollAreaWidgetContents)
        self.sliderSensitivity.setObjectName(u"sliderSensitivity")
        self.sliderSensitivity.setGeometry(QRect(180, 210, 271, 31))
        self.sliderSensitivity.setOrientation(Qt.Orientation.Horizontal)
        self.lblRadius = QLabel(self.scrollAreaWidgetContents)
        self.lblRadius.setObjectName(u"lblRadius")
        self.lblRadius.setGeometry(QRect(20, 250, 171, 30))
        self.spinRadius = QSpinBox(self.scrollAreaWidgetContents)
        self.spinRadius.setObjectName(u"spinRadius")
        self.spinRadius.setGeometry(QRect(390, 240, 60, 31))
        self.spinRadius.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lblDistance = QLabel(self.scrollAreaWidgetContents)
        self.lblDistance.setObjectName(u"lblDistance")
        self.lblDistance.setGeometry(QRect(20, 100, 191, 30))
        self.sliderDistance = QSlider(self.scrollAreaWidgetContents)
        self.sliderDistance.setObjectName(u"sliderDistance")
        self.sliderDistance.setGeometry(QRect(190, 100, 271, 31))
        self.sliderDistance.setOrientation(Qt.Orientation.Horizontal)
        self.lblFrameThrottling = QLabel(self.scrollAreaWidgetContents)
        self.lblFrameThrottling.setObjectName(u"lblFrameThrottling")
        self.lblFrameThrottling.setGeometry(QRect(20, 190, 271, 30))
        self.checkFrameThrottling = QCheckBox(self.scrollAreaWidgetContents)
        self.checkFrameThrottling.setObjectName(u"checkFrameThrottling")
        self.checkFrameThrottling.setGeometry(QRect(430, 190, 21, 22))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btnStartCam = QPushButton(self.frameButtons)
        self.btnStartCam.setObjectName(u"btnStartCam")
        self.btnStartCam.setGeometry(QRect(30, 340, 171, 41))
        self.scrollArea.raise_()
        self.btnBack.raise_()
        self.btnSave.raise_()
        self.btnStartCam.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.lblTitle.setText(QCoreApplication.translate("Form", u"GestureBoard", None))
        self.lblDescription.setText(QCoreApplication.translate("Form", u"Le\u00edr\u00e1s", None))
        self.lblCvImg.setText(QCoreApplication.translate("Form", u"TextLabel", None))
        self.btnBack.setText(QCoreApplication.translate("Form", u"Vissza", None))
        self.btnSave.setText(QCoreApplication.translate("Form", u"Ment\u00e9s", None))
        self.lblConfidence.setText(QCoreApplication.translate("Form", u"Magabiztoss\u00e1g", None))
        self.lblHue.setText(QCoreApplication.translate("Form", u"Sz\u00edneltol\u00e1s", None))
        self.lblCamera.setText(QCoreApplication.translate("Form", u"Kamera", None))
        self.lblFrameCnt.setText(QCoreApplication.translate("Form", u"K\u00e9pkocka gesztusonk\u00e9nt", None))
        self.lblDelay.setText(QCoreApplication.translate("Form", u"Sz\u00fcnet gesztusok k\u00f6z\u00f6tt", None))
        self.lblSensitivity.setText(QCoreApplication.translate("Form", u"Eg\u00e9r \u00e9rz\u00e9kenys\u00e9g", None))
        self.lblRadius.setText(QCoreApplication.translate("Form", u"Sodr\u00f3d\u00e1smentes z\u00f3na sugara", None))
        self.lblDistance.setText(QCoreApplication.translate("Form", u"T\u00e1vols\u00e1g", None))
        self.lblFrameThrottling.setText(QCoreApplication.translate("Form", u"Takar\u00e9kos m\u00f3d", None))
        self.checkFrameThrottling.setText("")
        self.btnStartCam.setText(QCoreApplication.translate("Form", u"Kamerateszt", None))
    # retranslateUi

