jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: ''
          requirements: ''
          upload_exe_with_name: 'Szakdolgozat Executable'
          options: >
            --noconfirm
            --filenames "./UI/main.py"
            --onefile False
            --windowed
            --icon "./UI/Resources/Icons/hand.ico"
            --clean False
            --strip False
            --noupx False
            --datas "./UI/Views;Views/"
            --datas "./UI/Resources;Resources/"
            --datas "./UI/Models;Models/"
            --datas "./UI/Controllers;Controllers/"
            --datas "./UI/Config;Config/"
            --exclude "PyQt6"
            --hidden-import "tensorflow"
      
      - name: Copy additional folders
        run: |
          mkdir -p ./output
          cp -r ./UI/Config ./output/Config
          cp -r ./UI/Data ./output/Data
          cp -r ./UI/Resources ./output/Resources
      
      - name: Upload output folder
        uses: actions/upload-artifact@v3
        with:
          name: Full Output
          path: ./output
