name: Test and Build

on: [workflow_dispatch, pull_request]

jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('./UI/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Set up virtual environment
        run: |
          python -m venv .venv
          .venv\Scripts\python.exe -m pip install --upgrade pip
          .venv\Scripts\pip.exe install -r ./UI/requirements.txt
          .venv\Scripts\pip.exe install pyinstaller pytest-github-actions-annotate-failures
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run tests
        run: .venv\Scripts\pytest.exe --disable-warnings

  Win64_Build:
    needs: Test
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: Restore virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('./UI/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Set up virtual environment
        run: |
          python -m venv .venv
          .venv\Scripts\python.exe -m pip install --upgrade pip
          .venv\Scripts\pip.exe install -r ./UI/requirements.txt
          .venv\Scripts\pip.exe install pyinstaller
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Build with PyInstaller
        shell: cmd
        run: |
          .venv\Scripts\pyinstaller ./UI/main.py ^
            --windowed ^
            --icon=./UI/Resources/Icons/hand.ico ^
            --hidden-import=tensorflow ^
            --noconfirm ^
            --clean ^
            --distpath ./build_dist

      - name: Copy config/data/resources
        run: |
          mkdir ./build_dist/Config
          mkdir ./build_dist/Data
          mkdir ./build_dist/Resources
          xcopy /E /I /Y .\UI\Config .\build_dist\Config
          xcopy /E /I /Y .\UI\Data .\build_dist\Data
          xcopy /E /I /Y .\UI\Resources .\build_dist\Resources

      - name: Clean up folder structure
        shell: cmd
        run: |
          xcopy /E /I /Y build_dist\main\* build_dist\
          rmdir /S /Q build_dist\main

      - name: Rename executable
        shell: cmd
        run: rename build_dist\main.exe GestureBoard.exe

      - name: Sign Executable
        uses: skymatic/code-sign-action@v3
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.PASSWORD }}'
          certificatesha1: '${{ secrets.CERTIFICATESHA1 }}'
          timestampUrl: 'http://timestamp.digicert.com'
          folder: 'build_dist'
          recursive: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GestureBoard_Windows64
          path: ./build_dist
