name: Test

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('./App/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
#
      - name: Set up virtual environment
        run: |
          python -m venv .venv
          .venv\Scripts\python.exe -m pip install --upgrade pip
          .venv\Scripts\pip.exe install -r ./App/requirements.txt
          .venv\Scripts\pip.exe install pytest-qt
          .venv\Scripts\pip.exe install pyinstaller pytest-cov pytest-github-actions-annotate-failures
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run tests with coverage
        id: tests
        run: .venv\Scripts\pytest.exe --disable-warnings --junitxml=pytest.xml --cov=App --cov=docker --cov-report=xml:coverage.xml

      - name: Pytest coverage comment
        if: always()
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml